// SPDX-License-Identifier: MIT
#ifndef GXNET_REGISTRY_HPP
#define GXNET_REGISTRY_HPP

#include <algorithm>
#include <cstddef>
#include <optional>
#include <span>
#include <string_view>

#include "gxnet/detail/registry_table.hpp"
#include "gxnet/detail/token_doc.hpp"
#include "gxnet/token.hpp"
#include "gxnet/version.hpp"

// Subfunction semantics are an optional second table, generated by
// tools/gen_docs.py from the vendor reference. That reference is not in this
// repository and neither is the table, so the accessors below are always
// declared and simply report nothing when it was never generated.
//
// The build system may have settled the question already, and when it has, its
// answer wins: a header that did not exist when a translation unit was first
// compiled is in none of its dependencies, so only something on the command
// line makes an incremental build notice that it exists now.
#if !defined(GXNET_HAS_TOKEN_DOCS) && defined(__has_include)
#if __has_include("gxnet/detail/registry_docs.hpp")
#define GXNET_HAS_TOKEN_DOCS 1
#endif
#endif

#ifdef GXNET_HAS_TOKEN_DOCS
#include "gxnet/detail/registry_docs.hpp"
#endif

namespace gxnet {

/// Lookup table built from the vendor subfunction reference.
///
/// The table carries names and introducing versions. What a value *means* is
/// kept apart, in the optional table behind GXNET_HAS_TOKEN_DOCS: for a number
/// of subfunctions the reference documents nothing beyond the name, and
/// inventing ranges would be worse than admitting the gap.
///
/// The whole table is constexpr, so a lookup written against a literal token is
/// resolved by the compiler and costs nothing at run time. See knownToken()
/// below for the compile-time form.
class Registry {
public:
    constexpr explicit Registry(std::span<const TokenInfo> entries) : entries_(entries) {}

    /// The table compiled into the library.
    static constexpr Registry builtin() { return Registry{detail::kRegistryTable}; }

    constexpr std::optional<TokenInfo> find(Token token) const {
        const auto it = std::lower_bound(entries_.begin(), entries_.end(), token,
                                         [](const TokenInfo& e, const Token& t) { return e.token < t; });
        if (it == entries_.end() || it->token != token) return std::nullopt;
        return *it;
    }

    constexpr std::optional<TokenInfo> findByName(std::string_view name) const {
        for (const TokenInfo& e : entries_) {
            if (e.name == name) return e;
        }
        return std::nullopt;
    }

    /// Every entry, ordered by token.
    constexpr std::span<const TokenInfo> entries() const { return entries_; }

    constexpr std::size_t size() const { return entries_.size(); }

private:
    std::span<const TokenInfo> entries_;
};

/// Convenience wrappers over Registry::builtin().
constexpr std::optional<std::string_view> tokenName(Token token) {
    const auto info = Registry::builtin().find(token);
    if (!info) return std::nullopt;
    return info->name;
}

constexpr std::optional<Token> tokenByName(std::string_view name) {
    const auto info = Registry::builtin().findByName(name);
    if (!info) return std::nullopt;
    return info->token;
}

/// What the reference says about a subfunction, when the optional table was
/// generated. Absent for roughly one token in seven: the reference lists those
/// without ever saying what they do.
constexpr std::optional<TokenDoc> tokenDoc([[maybe_unused]] Token token) {
#ifdef GXNET_HAS_TOKEN_DOCS
    const auto it = std::lower_bound(detail::kDocTable.begin(), detail::kDocTable.end(), token,
                                     [](const TokenDoc& e, const Token& t) { return e.token < t; });
    if (it != detail::kDocTable.end() && it->token == token) return *it;
#endif
    return std::nullopt;
}

/// What the subfunction is for, in the reference's own words. Named for the
/// meaning rather than "description", which elsewhere in this project is a
/// token's display label.
constexpr std::optional<std::string_view> tokenMeaning(Token token) {
    const auto doc = tokenDoc(token);
    if (!doc || doc->description.empty()) return std::nullopt;
    return doc->description;
}

/// The values the reference names for a subfunction. Empty for the majority,
/// which carry a plain number.
constexpr std::span<const TokenValue> tokenValues([[maybe_unused]] Token token) {
#ifdef GXNET_HAS_TOKEN_DOCS
    if (const auto doc = tokenDoc(token)) {
        return std::span<const TokenValue>(detail::kDocValues).subspan(doc->first_value, doc->value_count);
    }
#endif
    return {};
}

/// The meaning of one value, when the reference names it.
constexpr std::optional<std::string_view> tokenValueName(Token token, std::int32_t value) {
    for (const TokenValue& entry : tokenValues(token)) {
        if (entry.value == value) return entry.text;
    }
    return std::nullopt;
}

/// Compile-time lookup. A token that is well formed but absent from the table
/// fails to compile, which is the point: control sequences name their tokens as
/// string literals, and `"GW7E"_tok` instead of `"GW7D"_tok` would otherwise be
/// found out on a running line.
///
///     constexpr Token kUniqueData = knownToken("GGW_UNIQUE_DATEN");
///
/// Both spellings are accepted, the four character token and the symbolic name,
/// because the reference and the engineers who answer questions about it use
/// different ones.
consteval TokenInfo knownToken(std::string_view text) {
    if (const auto token = Token::parse(text)) {
        if (const auto info = Registry::builtin().find(*token)) return *info;
        throw "token is well formed but absent from the registry";
    }
    if (const auto info = Registry::builtin().findByName(text)) return *info;
    throw "neither a valid token nor a known symbolic name";
}

// The table must be sorted for find() to work, and it is emitted sorted by
// token text. That happens to match Token's member-wise ordering, but checking
// beats trusting: a future reference revision could introduce a token whose
// letters break the assumption.
static_assert(std::is_sorted(detail::kRegistryTable.begin(), detail::kRegistryTable.end(),
                             [](const TokenInfo& a, const TokenInfo& b) { return a.token < b.token; }),
              "registry table must be sorted by token");

}  // namespace gxnet

#endif  // GXNET_REGISTRY_HPP
