#!/usr/bin/env python3
"""Extract the GxNet token registry from the vendor reference (markdown export).

Usage:  python3 gen_registry.py GxNet.md > ../include/gxnet/detail/registry_table.hpp

The reference lists each subfunction as a heading holding the 4-character token,
followed by the symbolic name and (usually) the software version in which the
subfunction was introduced.  Entries with no description in the source are
flagged as ``reserved``.
"""

import re
import sys
import json

TOKEN_RE = re.compile(r'^(?:\*\*|#{1,6}\s*)([A-Z]{2}[0-9A-F]{2})(?:\*\*)?\s*$')
NAME_RE = re.compile(r'^([A-Z]{2,4}_[A-Z0-9_]+)\s*$')
VERSION_RE = re.compile(r'^(?:#{1,6}\s*)?(\d{1,2}\.\d{2})\b')
RESERVED_RE = re.compile(r'\breserved\b', re.IGNORECASE)


def extract(path):
    with open(path, encoding='utf-8') as fh:
        lines = fh.read().split('\n')

    out = {}
    for i, line in enumerate(lines):
        m = TOKEN_RE.match(line.strip())
        if not m:
            continue
        token = m.group(1)

        name = ''
        version = ''
        reserved = False
        # The name follows within a couple of lines; the version follows the name.
        for j in range(i + 1, min(i + 8, len(lines))):
            s = lines[j].strip().lstrip('#').strip()
            if not s or s == '```':
                continue
            if not name:
                nm = NAME_RE.match(s)
                if nm:
                    name = nm.group(1)
                    continue
                # A new token heading before a name means this entry has none.
                if TOKEN_RE.match(lines[j].strip()):
                    break
                continue
            vm = VERSION_RE.match(s)
            if vm:
                version = vm.group(1)
                if RESERVED_RE.search(s):
                    reserved = True
                break
            if TOKEN_RE.match(lines[j].strip()):
                break

        if not name:
            continue
        # Keep the first definition; later ones are cross-references.
        if token not in out:
            out[token] = {'token': token, 'name': name,
                          'version': version, 'reserved': reserved}
    return out


def emit_cpp(entries):
    # Sorted by the token text, which for two upper-case letters followed by two
    # upper-case hex digits is the same order as Token's member-wise <=>. The
    # header static_asserts this rather than trusting it.
    rows = sorted(entries.values(), key=lambda e: e['token'])
    print('// SPDX-License-Identifier: MIT')
    print('// Generated by tools/gen_registry.py -- do not edit by hand.')
    print('// Source: Bizerba GxNet subfunction reference.')
    print('#ifndef GXNET_DETAIL_REGISTRY_TABLE_HPP')
    print('#define GXNET_DETAIL_REGISTRY_TABLE_HPP')
    print('')
    print('#include <array>')
    print('')
    print('#include "gxnet/token.hpp"')
    print('#include "gxnet/version.hpp"')
    print('')
    print('namespace gxnet {')
    print('')
    print('/// A registry entry describing one subfunction.')
    print('struct TokenInfo {')
    print('    Token token;')
    print('    std::string_view name;  ///< symbolic name, e.g. "GGW_UNIQUE_DATEN"')
    print('    Version since;          ///< release that introduced it; invalid if unknown')
    print('    bool reserved = false;  ///< listed but undocumented in the reference')
    print('};')
    print('')
    print('namespace detail {')
    print('')
    print('// clang-format off')
    print('inline constexpr std::array<TokenInfo, %d> kRegistryTable{{' % len(rows))
    for e in rows:
        token = e['token']
        if e['version']:
            major, minor = e['version'].split('.')
            version = 'Version{%d, %d}' % (int(major), int(minor))
        else:
            version = 'Version{}'
        print("    {Token{'%s', '%s', 0x%s}, \"%s\", %s, %s}," % (
            token[0], token[1], token[2:4], e['name'], version,
            'true' if e['reserved'] else 'false'))
    print('}};')
    print('// clang-format on')
    print('')
    print('}  // namespace detail')
    print('}  // namespace gxnet')
    print('')
    print('#endif  // GXNET_DETAIL_REGISTRY_TABLE_HPP')


if __name__ == '__main__':
    src = sys.argv[1]
    data = extract(src)
    if len(sys.argv) > 2 and sys.argv[2] == '--json':
        json.dump(list(data.values()), sys.stdout, indent=1)
    else:
        emit_cpp(data)
    print('// entries: %d' % len(data), file=sys.stderr)
